### ISSUE TITLE
cannot find trait `ParserSource` in module `fbxbin` not found in `fbxbin`

### ISSUE THREAD

**Issue by lucasjinreal** [lo48576/fbx-tree-view#2]
cannot find trait `ParserSource` in module `fbxbin`
not found in `fbxbin`

**Comment by lucasjinreal** [comment]
Can u update this to your newest API? I can notice this changed into Reader, but Reader actually is private in your latest code......

**Comment by lo48576** [comment]
Did you modified `Cargo.toml` of fbx-tree-view?
That is actually a breaking change but both fbxcel and this utility follows semver rules, so build won't break in normal situation.

Anyway, updated dependency to fbxcel-0.9.0 by fe5df03d91664d40b72d45dc54191ee286d46a00.

**Comment by lucasjinreal** [comment]
Get it, thanks, now it can work
